[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "batchbpe"
version = "1.0.0"
description = "Safely batched, pure python BPE tokenizer. Forked from Andrej Karpathy's minbpe."
authors = [
    {name = "Alexander Morgan"},
    {name = "Andrej Karpathy"}
]
requires-python = ">=3.12"
dependencies = [
    "regex",
    "tiktoken",
    "requests",
    "pyarrow>=21.0.0",
    "psutil",
    "numpy>=2.0.2",
    "pytest>=8.4.2",
    "datasets>=5.0.1",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "matplotlib",
    "maturin>=1.7",
]

[tool.maturin]
module-name = "batchbpe._native"
python-source = "."

[tool.setuptools.packages.find]
include = ["batchbpe*"]
